---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: proxmox-cluster
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        overlay: testlab
  template:
    metadata:
      name: "cluster-{{overlay}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: "mgmt"
      ignoreDifferences: []
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 5m
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
      source:
        repoURL: https://github.com/Dayzpd/kustomize-proxmox-cluster
        targetRevision: HEAD
        path: "overlays/{{overlay}}"
      destination:
        name: "{{cluster}}"
