apiVersion: v1
data:
  namespace.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      creationTimestamp: null
      name: bitwarden
    spec: {}
    status: {}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: bitwarden-namespace
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: bitwarden-access-token
spec:
  encryptedData:
    secret.yaml: AgA27TkZ8U3DIc98LaYVUfRdgHi7um84O4E9ZuzrJutSgznBN3VpeJTr3sbqCji5/VqoPw0Ae2VuaRw4+dL5W4e69yeWDOuoIGnvGrW/9G32rXXoqaaoXMZrY2ZWm2EcARTzTNKv2KnGa3QGLXOB6EPavhfObesoLX17kdh3dPtSlb1VKw7kiV0WIiEX28eqE0OxVxeZd/CdZc8boq2/0oSFFQ/cVkM89So43AHimn/SPgvk3r6hLvuy+BwibnU2T50ZRFEJvin5qlK+XHFOJRmCdliyYc+utnpE+n0r55IhwTn6uMibrWweFeh59H3j8ynU7ODRvQLJ/+DS8M+hlR+eKTBhpCzvON1RTcoCtkgJtCF57CKWwoMtLSPomh5uOhhqqBOZZQkWMXKwJt/OL7XgANcPyGIuTxDn9miFU/AUfD58iEKW2DO3jWcUthL+DOoZMpWSGIz7efM2rVQyST9qmWJkK8i+u1CYDRfpwwr5eqbKuet3nEGqfDh9bdf0SErprOwqwsYZMLUg8yBosf1pqcoXeNMDq8Za4YP2mgDUBlZM5gHe7un2AIfbWsrB6Wl3dauJpZk24IZ5MPoQ7Q3OLGVWTaVdwqEbRCqm/qMmatJZbEcZx4hjytb+dNdwl8g9cSOUFrkGbkJCTDHgvwteHSB+bbOzax1djzAB9hBSAXm35+poV4nfIl1Xw3dXU21q5PdgBvLzbC3ohYBFAYTURIks1qlty5tT3I/GyAr0KgcDDqrq4NwVUZTuFggS453XWonCfoCChgECpzWGwhrR5PmLmW4JQirozuDbu0ooDca64oWRdDFalgTakQ8Z4qN1QTc4RITsMSJwgzu8RJQ5l+0oqgKd/UXpGFmrWj8NLwGTRb1MJZVXyuQCqE4Yin0s4valGlCxiM9/vTvtnUuLsacyX4KCCTKCa2mS4ljNx7+7ctdmKvaCL4rWl59w/JBtsX1t9quHCJluKUUhG/U2SXvbACSjxmCD1z/TqjqQT/zQ+tlx0BTEvHD9JMEAfqdNJ96CjUDbo3y6f64PJVnXZfJsTQLJ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: bitwarden-access-token
    type: addons.cluster.x-k8s.io/resource-set
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: bitwarden-addon
spec:
  clusterSelector:
    matchLabels:
      bitwardenAddon: enabled
  resources:
  - kind: ConfigMap
    name: bitwarden-namespace
  - kind: Secret
    name: bitwarden-access-token
  strategy: Reconcile
