apiVersion: v1
data:
  namespace.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      creationTimestamp: null
      name: external-secrets
    spec: {}
    status: {}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: external-secrets-namespace
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: bitwarden-access-token
spec:
  encryptedData:
    secret.yaml: AgBYBLdXPZrJfhrtoxWbvy8S474bLiUNnDv7+jWRIxIbj/ADDX5yk7mRO45dv3+CgGse4ZL5X4L05nEFR+lhQpF59xgzGkIn0OhAwjJ4ZkQNUrmMJWbVJ5mgHe7ovwrDioRpdUjO+p8rsL8etMz2kgKF4E1p8DZvlbAQfrGUgcDSXGnhqOixoC2XLpH3ojIesVB2MdaeSA2z41C4oCVelSKrOfNyq/7GUndsyRlKAgmFSMgeqFJtyIXC593sd7QOl6m8fyigoTcMVjthznA8NEKQAxZqytuN3JNtw+WSotYe5SiZguswveh5plDqFnZ2RkvW8Sghipee9i4skMiuwpdjJQjQYk5faktmwed33lgxvGAnSeB1OVue920BLv1WdwSSgWVPORIKuTz3LQ20/hVjUQnmdBIdflFi6IzA/VUSv8Ow4DGk2cOOy3VpGywyaT6gMHiOVzmGCJ551e9NomSl8GMk2db6B3jEkaMSyfRUPJRxY80ictcmCQvC4cCKUYv2k0h0AuJgH8gRfZ9mARECkmtoY/Es10H6LR1a9WhRi8NyhLZ+8b7qc3GLAK+CcrBS+sYlKm1XpcrJDA4ac5hOAK/71psE1PJFCbh9u54uNuz9eBYRJT6BZfxbdt0ev8zJ52IfKPD66R5/1jycBEc+lHSuM+Kw2CfcljZiHomJhUwE4UiHrhb2W+bRAxBXJXX2X34ARxPSa5sID7ukqXHxKBRj2xTvjzNf8hiu/6TCCAEIsvdc9I6399YLlZxq5sNTWw+nftXWh4KaDwr1PysUVfrY48vi7nWu68cQSSfw+SWhJd1nM8torxc7DYF7OJnmM+eNeIHN8KukniBAjVCjuRpcvtnhEuILTBFMGlHhOjCLJhGSQv0zqJ3Vgcui99LqLfoE7y9XTFlpJqErxjS78uldCkmgsgmcNgXC6eQIea/5y6SnML+C3csbn7AVU/vb+mW0A1yTI+C7ZYLhocSJfhOEog59MOxN/263cGwd9d23UWJK8tPhTr7ow4BaovlG5TUd6xkZqKD+oThYNTnVzNL1zHU2nLdNZlMqJg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: bitwarden-access-token
    type: addons.cluster.x-k8s.io/resource-set
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: bitwarden-addon
spec:
  clusterSelector:
    matchLabels:
      bitwardenAddon: enabled
  resources:
  - kind: ConfigMap
    name: bitwarden-namespace
  - kind: Secret
    name: bitwarden-access-token
  strategy: Reconcile
