apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-proxmox-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: prod
  ignoreDifferences: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: https://github.com/Dayzpd/kustomize-proxmox-cluster
    targetRevision: HEAD
    path: overlays/prodlab
  destination:
    name: in-cluster